/*
 * This file is generated by jOOQ.
 */
package com.example.airtimemanagement.jooq.tables;


import com.example.airtimemanagement.jooq.AirtimeManager;
import com.example.airtimemanagement.jooq.Keys;
import com.example.airtimemanagement.jooq.tables.records.DistributorsRecord;

import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function4;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row4;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Distributors extends TableImpl<DistributorsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>airtime_manager.distributors</code>
     */
    public static final Distributors DISTRIBUTORS = new Distributors();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DistributorsRecord> getRecordType() {
        return DistributorsRecord.class;
    }

    /**
     * The column <code>airtime_manager.distributors.id</code>.
     */
    public final TableField<DistributorsRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>airtime_manager.distributors.name</code>.
     */
    public final TableField<DistributorsRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>airtime_manager.distributors.region</code>.
     */
    public final TableField<DistributorsRecord, String> REGION = createField(DSL.name("region"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>airtime_manager.distributors.max_serial_numbers</code>.
     */
    public final TableField<DistributorsRecord, Integer> MAX_SERIAL_NUMBERS = createField(DSL.name("max_serial_numbers"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("1000"), SQLDataType.INTEGER)), this, "");

    private Distributors(Name alias, Table<DistributorsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Distributors(Name alias, Table<DistributorsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>airtime_manager.distributors</code> table
     * reference
     */
    public Distributors(String alias) {
        this(DSL.name(alias), DISTRIBUTORS);
    }

    /**
     * Create an aliased <code>airtime_manager.distributors</code> table
     * reference
     */
    public Distributors(Name alias) {
        this(alias, DISTRIBUTORS);
    }

    /**
     * Create a <code>airtime_manager.distributors</code> table reference
     */
    public Distributors() {
        this(DSL.name("distributors"), null);
    }

    public <O extends Record> Distributors(Table<O> child, ForeignKey<O, DistributorsRecord> key) {
        super(child, key, DISTRIBUTORS);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : AirtimeManager.AIRTIME_MANAGER;
    }

    @Override
    public Identity<DistributorsRecord, Long> getIdentity() {
        return (Identity<DistributorsRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<DistributorsRecord> getPrimaryKey() {
        return Keys.KEY_DISTRIBUTORS_PRIMARY;
    }

    @Override
    public Distributors as(String alias) {
        return new Distributors(DSL.name(alias), this);
    }

    @Override
    public Distributors as(Name alias) {
        return new Distributors(alias, this);
    }

    @Override
    public Distributors as(Table<?> alias) {
        return new Distributors(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Distributors rename(String name) {
        return new Distributors(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Distributors rename(Name name) {
        return new Distributors(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Distributors rename(Table<?> name) {
        return new Distributors(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<Long, String, String, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function4<? super Long, ? super String, ? super String, ? super Integer, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function4<? super Long, ? super String, ? super String, ? super Integer, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
