/*
 * This file is generated by jOOQ.
 */
package com.example.airtimemanagement.jooq.tables;


import com.example.airtimemanagement.jooq.AirtimeManager;
import com.example.airtimemanagement.jooq.Keys;
import com.example.airtimemanagement.jooq.tables.records.SerialNumbersRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function5;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row5;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SerialNumbers extends TableImpl<SerialNumbersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>airtime_manager.serial_numbers</code>
     */
    public static final SerialNumbers SERIAL_NUMBERS = new SerialNumbers();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SerialNumbersRecord> getRecordType() {
        return SerialNumbersRecord.class;
    }

    /**
     * The column <code>airtime_manager.serial_numbers.id</code>.
     */
    public final TableField<SerialNumbersRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>airtime_manager.serial_numbers.serial_number</code>.
     */
    public final TableField<SerialNumbersRecord, String> SERIAL_NUMBER = createField(DSL.name("serial_number"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>airtime_manager.serial_numbers.distributor_id</code>.
     */
    public final TableField<SerialNumbersRecord, Long> DISTRIBUTOR_ID = createField(DSL.name("distributor_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>airtime_manager.serial_numbers.status</code>.
     */
    public final TableField<SerialNumbersRecord, String> STATUS = createField(DSL.name("status"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>airtime_manager.serial_numbers.created_at</code>.
     */
    public final TableField<SerialNumbersRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(0).nullable(false), this, "");

    private SerialNumbers(Name alias, Table<SerialNumbersRecord> aliased) {
        this(alias, aliased, null);
    }

    private SerialNumbers(Name alias, Table<SerialNumbersRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>airtime_manager.serial_numbers</code> table
     * reference
     */
    public SerialNumbers(String alias) {
        this(DSL.name(alias), SERIAL_NUMBERS);
    }

    /**
     * Create an aliased <code>airtime_manager.serial_numbers</code> table
     * reference
     */
    public SerialNumbers(Name alias) {
        this(alias, SERIAL_NUMBERS);
    }

    /**
     * Create a <code>airtime_manager.serial_numbers</code> table reference
     */
    public SerialNumbers() {
        this(DSL.name("serial_numbers"), null);
    }

    public <O extends Record> SerialNumbers(Table<O> child, ForeignKey<O, SerialNumbersRecord> key) {
        super(child, key, SERIAL_NUMBERS);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : AirtimeManager.AIRTIME_MANAGER;
    }

    @Override
    public Identity<SerialNumbersRecord, Long> getIdentity() {
        return (Identity<SerialNumbersRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<SerialNumbersRecord> getPrimaryKey() {
        return Keys.KEY_SERIAL_NUMBERS_PRIMARY;
    }

    @Override
    public List<UniqueKey<SerialNumbersRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_SERIAL_NUMBERS_SERIAL_NUMBER);
    }

    @Override
    public List<ForeignKey<SerialNumbersRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_SERIAL_NUMBERS_DISTRIBUTOR);
    }

    private transient Distributors _distributors;

    /**
     * Get the implicit join path to the
     * <code>airtime_manager.distributors</code> table.
     */
    public Distributors distributors() {
        if (_distributors == null)
            _distributors = new Distributors(this, Keys.FK_SERIAL_NUMBERS_DISTRIBUTOR);

        return _distributors;
    }

    @Override
    public SerialNumbers as(String alias) {
        return new SerialNumbers(DSL.name(alias), this);
    }

    @Override
    public SerialNumbers as(Name alias) {
        return new SerialNumbers(alias, this);
    }

    @Override
    public SerialNumbers as(Table<?> alias) {
        return new SerialNumbers(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public SerialNumbers rename(String name) {
        return new SerialNumbers(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SerialNumbers rename(Name name) {
        return new SerialNumbers(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public SerialNumbers rename(Table<?> name) {
        return new SerialNumbers(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row5 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row5<Long, String, Long, String, LocalDateTime> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function5<? super Long, ? super String, ? super Long, ? super String, ? super LocalDateTime, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function5<? super Long, ? super String, ? super Long, ? super String, ? super LocalDateTime, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
