/*
 * This file is generated by jOOQ.
 */
package com.example.airtimemanagement.jooq;


import com.example.airtimemanagement.jooq.tables.Databasechangelog;
import com.example.airtimemanagement.jooq.tables.Databasechangeloglock;
import com.example.airtimemanagement.jooq.tables.Distributors;
import com.example.airtimemanagement.jooq.tables.Roles;
import com.example.airtimemanagement.jooq.tables.SerialNumbers;
import com.example.airtimemanagement.jooq.tables.UserRoles;
import com.example.airtimemanagement.jooq.tables.Users;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AirtimeManager extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>airtime_manager</code>
     */
    public static final AirtimeManager AIRTIME_MANAGER = new AirtimeManager();

    /**
     * The table <code>airtime_manager.DATABASECHANGELOG</code>.
     */
    public final Databasechangelog DATABASECHANGELOG = Databasechangelog.DATABASECHANGELOG;

    /**
     * The table <code>airtime_manager.DATABASECHANGELOGLOCK</code>.
     */
    public final Databasechangeloglock DATABASECHANGELOGLOCK = Databasechangeloglock.DATABASECHANGELOGLOCK;

    /**
     * The table <code>airtime_manager.distributors</code>.
     */
    public final Distributors DISTRIBUTORS = Distributors.DISTRIBUTORS;

    /**
     * The table <code>airtime_manager.roles</code>.
     */
    public final Roles ROLES = Roles.ROLES;

    /**
     * The table <code>airtime_manager.serial_numbers</code>.
     */
    public final SerialNumbers SERIAL_NUMBERS = SerialNumbers.SERIAL_NUMBERS;

    /**
     * The table <code>airtime_manager.user_roles</code>.
     */
    public final UserRoles USER_ROLES = UserRoles.USER_ROLES;

    /**
     * The table <code>airtime_manager.users</code>.
     */
    public final Users USERS = Users.USERS;

    /**
     * No further instances allowed
     */
    private AirtimeManager() {
        super("airtime_manager", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Databasechangelog.DATABASECHANGELOG,
            Databasechangeloglock.DATABASECHANGELOGLOCK,
            Distributors.DISTRIBUTORS,
            Roles.ROLES,
            SerialNumbers.SERIAL_NUMBERS,
            UserRoles.USER_ROLES,
            Users.USERS
        );
    }
}
