/*
 * This file is generated by jOOQ.
 */
package com.example.airtimemanagement.jooq;


import com.example.airtimemanagement.jooq.tables.Databasechangeloglock;
import com.example.airtimemanagement.jooq.tables.Distributors;
import com.example.airtimemanagement.jooq.tables.Roles;
import com.example.airtimemanagement.jooq.tables.SerialNumbers;
import com.example.airtimemanagement.jooq.tables.UserRoles;
import com.example.airtimemanagement.jooq.tables.Users;
import com.example.airtimemanagement.jooq.tables.records.DatabasechangeloglockRecord;
import com.example.airtimemanagement.jooq.tables.records.DistributorsRecord;
import com.example.airtimemanagement.jooq.tables.records.RolesRecord;
import com.example.airtimemanagement.jooq.tables.records.SerialNumbersRecord;
import com.example.airtimemanagement.jooq.tables.records.UserRolesRecord;
import com.example.airtimemanagement.jooq.tables.records.UsersRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * airtime_manager.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<DatabasechangeloglockRecord> KEY_DATABASECHANGELOGLOCK_PRIMARY = Internal.createUniqueKey(Databasechangeloglock.DATABASECHANGELOGLOCK, DSL.name("KEY_DATABASECHANGELOGLOCK_PRIMARY"), new TableField[] { Databasechangeloglock.DATABASECHANGELOGLOCK.ID }, true);
    public static final UniqueKey<DistributorsRecord> KEY_DISTRIBUTORS_PRIMARY = Internal.createUniqueKey(Distributors.DISTRIBUTORS, DSL.name("KEY_distributors_PRIMARY"), new TableField[] { Distributors.DISTRIBUTORS.ID }, true);
    public static final UniqueKey<RolesRecord> KEY_ROLES_NAME = Internal.createUniqueKey(Roles.ROLES, DSL.name("KEY_roles_name"), new TableField[] { Roles.ROLES.NAME }, true);
    public static final UniqueKey<RolesRecord> KEY_ROLES_PRIMARY = Internal.createUniqueKey(Roles.ROLES, DSL.name("KEY_roles_PRIMARY"), new TableField[] { Roles.ROLES.ID }, true);
    public static final UniqueKey<SerialNumbersRecord> KEY_SERIAL_NUMBERS_PRIMARY = Internal.createUniqueKey(SerialNumbers.SERIAL_NUMBERS, DSL.name("KEY_serial_numbers_PRIMARY"), new TableField[] { SerialNumbers.SERIAL_NUMBERS.ID }, true);
    public static final UniqueKey<SerialNumbersRecord> KEY_SERIAL_NUMBERS_SERIAL_NUMBER = Internal.createUniqueKey(SerialNumbers.SERIAL_NUMBERS, DSL.name("KEY_serial_numbers_serial_number"), new TableField[] { SerialNumbers.SERIAL_NUMBERS.SERIAL_NUMBER }, true);
    public static final UniqueKey<UserRolesRecord> KEY_USER_ROLES_PRIMARY = Internal.createUniqueKey(UserRoles.USER_ROLES, DSL.name("KEY_user_roles_PRIMARY"), new TableField[] { UserRoles.USER_ROLES.USER_ID, UserRoles.USER_ROLES.ROLE_ID }, true);
    public static final UniqueKey<UsersRecord> KEY_USERS_PRIMARY = Internal.createUniqueKey(Users.USERS, DSL.name("KEY_users_PRIMARY"), new TableField[] { Users.USERS.ID }, true);
    public static final UniqueKey<UsersRecord> KEY_USERS_USERNAME = Internal.createUniqueKey(Users.USERS, DSL.name("KEY_users_username"), new TableField[] { Users.USERS.USERNAME }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<SerialNumbersRecord, DistributorsRecord> FK_SERIAL_NUMBERS_DISTRIBUTOR = Internal.createForeignKey(SerialNumbers.SERIAL_NUMBERS, DSL.name("fk_serial_numbers_distributor"), new TableField[] { SerialNumbers.SERIAL_NUMBERS.DISTRIBUTOR_ID }, Keys.KEY_DISTRIBUTORS_PRIMARY, new TableField[] { Distributors.DISTRIBUTORS.ID }, true);
    public static final ForeignKey<UserRolesRecord, RolesRecord> FK_USER_ROLES_ROLE = Internal.createForeignKey(UserRoles.USER_ROLES, DSL.name("fk_user_roles_role"), new TableField[] { UserRoles.USER_ROLES.ROLE_ID }, Keys.KEY_ROLES_PRIMARY, new TableField[] { Roles.ROLES.ID }, true);
    public static final ForeignKey<UserRolesRecord, UsersRecord> FK_USER_ROLES_USER = Internal.createForeignKey(UserRoles.USER_ROLES, DSL.name("fk_user_roles_user"), new TableField[] { UserRoles.USER_ROLES.USER_ID }, Keys.KEY_USERS_PRIMARY, new TableField[] { Users.USERS.ID }, true);
}
