/*
 * This file is generated by jOOQ.
 */
package com.example.airtimemanagement.jooq;


import com.example.airtimemanagement.jooq.tables.Databasechangelog;
import com.example.airtimemanagement.jooq.tables.Databasechangeloglock;
import com.example.airtimemanagement.jooq.tables.Distributors;
import com.example.airtimemanagement.jooq.tables.Roles;
import com.example.airtimemanagement.jooq.tables.SerialNumbers;
import com.example.airtimemanagement.jooq.tables.UserRoles;
import com.example.airtimemanagement.jooq.tables.Users;


/**
 * Convenience access to all tables in airtime_manager.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>airtime_manager.DATABASECHANGELOG</code>.
     */
    public static final Databasechangelog DATABASECHANGELOG = Databasechangelog.DATABASECHANGELOG;

    /**
     * The table <code>airtime_manager.DATABASECHANGELOGLOCK</code>.
     */
    public static final Databasechangeloglock DATABASECHANGELOGLOCK = Databasechangeloglock.DATABASECHANGELOGLOCK;

    /**
     * The table <code>airtime_manager.distributors</code>.
     */
    public static final Distributors DISTRIBUTORS = Distributors.DISTRIBUTORS;

    /**
     * The table <code>airtime_manager.roles</code>.
     */
    public static final Roles ROLES = Roles.ROLES;

    /**
     * The table <code>airtime_manager.serial_numbers</code>.
     */
    public static final SerialNumbers SERIAL_NUMBERS = SerialNumbers.SERIAL_NUMBERS;

    /**
     * The table <code>airtime_manager.user_roles</code>.
     */
    public static final UserRoles USER_ROLES = UserRoles.USER_ROLES;

    /**
     * The table <code>airtime_manager.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
