/*
 * This file is generated by jOOQ.
 */
package com.example.airtimemanagement.jooq.tables.records;


import com.example.airtimemanagement.jooq.tables.Distributors;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DistributorsRecord extends UpdatableRecordImpl<DistributorsRecord> implements Record4<Long, String, String, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>airtime_manager.distributors.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>airtime_manager.distributors.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>airtime_manager.distributors.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>airtime_manager.distributors.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>airtime_manager.distributors.region</code>.
     */
    public void setRegion(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>airtime_manager.distributors.region</code>.
     */
    public String getRegion() {
        return (String) get(2);
    }

    /**
     * Setter for <code>airtime_manager.distributors.max_serial_numbers</code>.
     */
    public void setMaxSerialNumbers(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>airtime_manager.distributors.max_serial_numbers</code>.
     */
    public Integer getMaxSerialNumbers() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Long, String, String, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Long, String, String, Integer> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Distributors.DISTRIBUTORS.ID;
    }

    @Override
    public Field<String> field2() {
        return Distributors.DISTRIBUTORS.NAME;
    }

    @Override
    public Field<String> field3() {
        return Distributors.DISTRIBUTORS.REGION;
    }

    @Override
    public Field<Integer> field4() {
        return Distributors.DISTRIBUTORS.MAX_SERIAL_NUMBERS;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getRegion();
    }

    @Override
    public Integer component4() {
        return getMaxSerialNumbers();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getRegion();
    }

    @Override
    public Integer value4() {
        return getMaxSerialNumbers();
    }

    @Override
    public DistributorsRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public DistributorsRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public DistributorsRecord value3(String value) {
        setRegion(value);
        return this;
    }

    @Override
    public DistributorsRecord value4(Integer value) {
        setMaxSerialNumbers(value);
        return this;
    }

    @Override
    public DistributorsRecord values(Long value1, String value2, String value3, Integer value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DistributorsRecord
     */
    public DistributorsRecord() {
        super(Distributors.DISTRIBUTORS);
    }

    /**
     * Create a detached, initialised DistributorsRecord
     */
    public DistributorsRecord(Long id, String name, String region, Integer maxSerialNumbers) {
        super(Distributors.DISTRIBUTORS);

        setId(id);
        setName(name);
        setRegion(region);
        setMaxSerialNumbers(maxSerialNumbers);
    }
}
