/*
 * This file is generated by jOOQ.
 */
package com.example.airtimemanagement.jooq.tables.records;


import com.example.airtimemanagement.jooq.tables.SerialNumbers;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SerialNumbersRecord extends UpdatableRecordImpl<SerialNumbersRecord> implements Record5<Long, String, Long, String, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>airtime_manager.serial_numbers.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>airtime_manager.serial_numbers.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>airtime_manager.serial_numbers.serial_number</code>.
     */
    public void setSerialNumber(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>airtime_manager.serial_numbers.serial_number</code>.
     */
    public String getSerialNumber() {
        return (String) get(1);
    }

    /**
     * Setter for <code>airtime_manager.serial_numbers.distributor_id</code>.
     */
    public void setDistributorId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>airtime_manager.serial_numbers.distributor_id</code>.
     */
    public Long getDistributorId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>airtime_manager.serial_numbers.status</code>.
     */
    public void setStatus(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>airtime_manager.serial_numbers.status</code>.
     */
    public String getStatus() {
        return (String) get(3);
    }

    /**
     * Setter for <code>airtime_manager.serial_numbers.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>airtime_manager.serial_numbers.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Long, String, Long, String, LocalDateTime> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Long, String, Long, String, LocalDateTime> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return SerialNumbers.SERIAL_NUMBERS.ID;
    }

    @Override
    public Field<String> field2() {
        return SerialNumbers.SERIAL_NUMBERS.SERIAL_NUMBER;
    }

    @Override
    public Field<Long> field3() {
        return SerialNumbers.SERIAL_NUMBERS.DISTRIBUTOR_ID;
    }

    @Override
    public Field<String> field4() {
        return SerialNumbers.SERIAL_NUMBERS.STATUS;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return SerialNumbers.SERIAL_NUMBERS.CREATED_AT;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getSerialNumber();
    }

    @Override
    public Long component3() {
        return getDistributorId();
    }

    @Override
    public String component4() {
        return getStatus();
    }

    @Override
    public LocalDateTime component5() {
        return getCreatedAt();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getSerialNumber();
    }

    @Override
    public Long value3() {
        return getDistributorId();
    }

    @Override
    public String value4() {
        return getStatus();
    }

    @Override
    public LocalDateTime value5() {
        return getCreatedAt();
    }

    @Override
    public SerialNumbersRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public SerialNumbersRecord value2(String value) {
        setSerialNumber(value);
        return this;
    }

    @Override
    public SerialNumbersRecord value3(Long value) {
        setDistributorId(value);
        return this;
    }

    @Override
    public SerialNumbersRecord value4(String value) {
        setStatus(value);
        return this;
    }

    @Override
    public SerialNumbersRecord value5(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public SerialNumbersRecord values(Long value1, String value2, Long value3, String value4, LocalDateTime value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SerialNumbersRecord
     */
    public SerialNumbersRecord() {
        super(SerialNumbers.SERIAL_NUMBERS);
    }

    /**
     * Create a detached, initialised SerialNumbersRecord
     */
    public SerialNumbersRecord(Long id, String serialNumber, Long distributorId, String status, LocalDateTime createdAt) {
        super(SerialNumbers.SERIAL_NUMBERS);

        setId(id);
        setSerialNumber(serialNumber);
        setDistributorId(distributorId);
        setStatus(status);
        setCreatedAt(createdAt);
    }
}
